// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwhrruvcjrytkeecrbuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3aHJydXZjanJ5dGtlZWNyYnV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NzMwNDMsImV4cCI6MjA2NDI0OTA0M30.XjE2dfEngx5C50_zqTvdnGOfPvto6Z996FQvN0cfA8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);